repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml
      - id: check-added-large-files
      - id: name-tests-test

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.5.1'
    hooks:
      - id: mypy
        args: [
          --no-strict-optional,
          --ignore-missing-imports,
          --scripts-are-modules,
          --explicit-package-bases
        ]
        exclude: tests

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: [ --profile, black, --filter-files ]

  - repo: https://github.com/grantjenks/blue
    rev: v0.9.1
    hooks:
      - id: blue
        name: blue
        description: "Blue: The somewhat less uncompromising Python code formatter"
        entry: blue
        language: python
        language_version: python3
        minimum_pre_commit_version: 2.9.2
        require_serial: true
        types_or: [ python, pyi ]

  - repo: https://github.com/pycqa/flake8
    rev: '6.1.0'
    hooks:
      - id: flake8
